security:
  firewalls:       
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        context: dev
        security: false
        
    secured_area:
        pattern: ^/
        anonymous: ~
        form_login:
             login_path: /login
             check_path: /autenticar
             post_only:   true
             always_use_default_target_path: true
             default_target_path: /
             username_parameter: form[_username]
             password_parameter: form[_password]
        logout:
             path: /logout 
             target: /login
             invalidate_session: true
             delete_cookies:
                    name:
                       path: ~
                       domain: ~
  access_control: 
    - { path: ^/login*, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
    - { path: ^/*, roles: [ROLE_USER, ROLE_ADJUNTO, ROLE_SECRETARIO, ROLE_PREFEITO, ROLE_PRENSA, ROLE_ADMIN] }
    - { path: ^/admin*, roles: [ROLE_ADJUNTO, ROLE_SECRETARIO, ROLE_PREFEITO, ROLE_PRENSA, ROLE_ADMIN] }
    - { path: ^/admin/banners*, roles: [ROLE_PRENSA, ROLE_ADMIN] }
#    - { path: ^/perfil, roles: ROLE_USER }
#    - { path: ^/admin/usuarios, roles: [ROLE_ADMIN, ROLE_ENLACE] }
#    - { path: ^/admin, roles: ROLE_ADMIN }    
          
  providers:        
     base_datos:
         entity: {class: PmcIntranetBundle:Usuario}
 
  role_hierarchy:
        ROLE_ADJUNTO: [ROLE_USER]
        ROLE_SECRETARIO: [ROLE_USER, ROLE_ADJUNTO]
        ROLE_PREFEITO: [ROLE_USER, ROLE_ADJUNTO, ROLE_SECRETARIO]
        ROLE_PRENSA: [ROLE_USER, ROLE_ADJUNTO, ROLE_SECRETARIO, ROLE_PREFEITO]
        ROLE_ADMIN:  [ROLE_USER, ROLE_ADJUNTO, ROLE_SECRETARIO, ROLE_PREFEITO, ROLE_PRENSA]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

  encoders:     
     Pmc\IntranetBundle\Entity\Usuario:
           algorithm:        sha1
           encode_as_base64: false
           iterations:       1   
