home:
   pattern: /
   defaults: { _controller: PmcIntranetBundle:Home:home }

login:
   pattern: /login
   defaults: { _controller: PmcIntranetBundle:Access:login }
   
check_path:
   pattern: /autenticar
   
logout:
    pattern: /logout 

salida:
   pattern: /login/salida
   defaults: { _controller: PmcIntranetBundle:Access:salida }
   
borrarCache:   
   pattern: /login/borrarCache
   defaults: { _controller: PmcIntranetBundle:Access:borrarCache }
   
borrarCacheTwig:   
   pattern: /login/borrarCacheTwig
   defaults: { _controller: PmcIntranetBundle:Access:borrarCacheTwig }   
 
ativarConta:
   pattern: /login/ativar
   defaults: { _controller: PmcIntranetBundle:Access:ativarConta }
   
esqueciSenha:
   pattern: /login/esqueciSenha
   defaults: { _controller: PmcIntranetBundle:Access:esqueciSenha }
   
cambiarSenha:
   pattern: /cambiarSenha
   defaults: { _controller: PmcIntranetBundle:Funcionario:cambiarSenha }   
   
postarComentario:
   pattern: /ajax/postarComentario
   defaults: { _controller: PmcIntranetBundle:Home:postarComentario }
   
excluirComentario:
   pattern: /ajax/excluirComentario
   defaults: { _controller: PmcIntranetBundle:Home:excluirComentario } 

refrescarComentarios:
   pattern: /ajax/refrescarComentarios
   defaults: { _controller: PmcIntranetBundle:Home:refrescarComentarios }  
   
postarComentarioSolicitacao:
   pattern: /ajax/postarComentarioSolicitacao
   defaults: { _controller: PmcIntranetBundle:ServicoSolicitado:postarComentario }
   
excluirComentarioSolicitacao:
   pattern: /ajax/excluirComentarioSolicitacao
   defaults: { _controller: PmcIntranetBundle:ServicoSolicitado:excluirComentario } 

refrescarComentariosSolicitacao:
   pattern: /ajax/refrescarComentariosSolicitacao
   defaults: { _controller: PmcIntranetBundle:ServicoSolicitado:refrescarComentarios }
   
postarComentarioAviso:
   pattern: /ajax/postarComentarioAviso
   defaults: { _controller: PmcIntranetBundle:Avisos:postarComentario }
   
excluirComentarioAviso:
   pattern: /ajax/excluirComentarioAviso
   defaults: { _controller: PmcIntranetBundle:Avisos:excluirComentario } 

refrescarComentariosAviso:
   pattern: /ajax/refrescarComentariosAviso
   defaults: { _controller: PmcIntranetBundle:Avisos:refrescarComentarios }   
   
excluirPublicacao:
   pattern: /ajax/excluirPublicacao
   defaults: { _controller: PmcIntranetBundle:Home:excluirPublicacao }      

filtroRojo:
   pattern: /home
   defaults: { _controller: PmcIntranetBundle:Home:filtroRojo }
   
filtrar:
   pattern: /filtrar/{tipo}
   defaults: { _controller: PmcIntranetBundle:Social:filtrar }   
   
minhaRede:
   pattern: /minhaRede
   defaults: { _controller: PmcIntranetBundle:Social:minhaRede }
   
seguir:
   pattern: /ajax/seguir
   defaults: { _controller: PmcIntranetBundle:Social:seguir }   
   
adminBanners:
   pattern: /admin/banners
   defaults: { _controller: PmcIntranetBundle:Banner:adminBanners }   
   
log:
   pattern: /admin/log
   defaults: { _controller: PmcIntranetBundle:Log:listar }    
   
activarBanner:
   pattern: /ajax/activarBanner
   defaults: { _controller: PmcIntranetBundle:Banner:activarBanner } 
   
actualizaOrden:
   pattern: /ajax/actualizaOrden
   defaults: { _controller: PmcIntranetBundle:Banner:actualizaOrden }   
   
excluirBanner:
   pattern: /ajax/excluirBanner
   defaults: { _controller: PmcIntranetBundle:Banner:excluirBanner }    

editarBanner:
   pattern: /admin/banners/editar/{id}
   defaults: { _controller: PmcIntranetBundle:Banner:editarBanner, id: null } 
   
novoBanner:
   pattern: /admin/banners/novo
   defaults: { _controller: PmcIntranetBundle:Banner:novoBanner }    
   
linksUteis:
   pattern: /linkUteis
   defaults: { _controller: PmcIntranetBundle:LinkUteis:listarLinksUteis } 
   
excluirLinkUteis:
   pattern: /ajax/excluirLinkUteis
   defaults: { _controller: PmcIntranetBundle:LinkUteis:excluirLinkUteis }   
   
novoLinkUteis:
   pattern: /admin/linkUteis/novo
   defaults: { _controller: PmcIntranetBundle:LinkUteis:novoLinkUteis }
   
editarLinkUteis:
   pattern: /admin/linkUteis/editar/{id}
   defaults: { _controller: PmcIntranetBundle:LinkUteis:editarLinkUteis, id: null }   
   
leiDecreto:
   pattern: /leiDecreto
   defaults: { _controller: PmcIntranetBundle:LeiDecreto:listarLeiDecreto } 
   
excluirLeiDecreto:
   pattern: /ajax/excluirLeiDecreto
   defaults: { _controller: PmcIntranetBundle:LeiDecreto:excluirLeiDecreto }   
   
novoLeiDecreto:
   pattern: /admin/leiDecreto/novo
   defaults: { _controller: PmcIntranetBundle:LeiDecreto:novoLeiDecreto }
   
editarLeiDecreto:
   pattern: /admin/leiDecreto/editar/{id}
   defaults: { _controller: PmcIntranetBundle:LeiDecreto:editarLeiDecreto, id: null }   

funcionarios:
   pattern: /funcionarios
   defaults: { _controller: PmcIntranetBundle:Funcionario:listarFuncionarios }
   
novoFuncionario:
   pattern: /admin/funcionarios/novo
   defaults: { _controller: PmcIntranetBundle:Funcionario:novoFuncionario }

editarFuncionario:
   pattern: /admin/funcionarios/editar/{id}
   defaults: { _controller: PmcIntranetBundle:Funcionario:editarFuncionario, id: null }  

perfilFuncionario:
   pattern: /funcionarios/perfil/{user}
   defaults: { _controller: PmcIntranetBundle:Funcionario:perfilFuncionario, user: null }
   
secretarias:
   pattern: /secretarias
   defaults: { _controller: PmcIntranetBundle:Secretaria:listarSecretarias }
   
novaSecretaria:
   pattern: /admin/secretarias/nova
   defaults: { _controller: PmcIntranetBundle:Secretaria:novaSecretaria }

editarSecretaria:
   pattern: /admin/secretarias/editar/{id}
   defaults: { _controller: PmcIntranetBundle:Secretaria:editarSecretaria, id: null } 
   
excluirSecretaria:
   pattern: /ajax/excluirSecretaria
   defaults: { _controller: PmcIntranetBundle:Secretaria:excluirSecretaria }     
   
servicos:
   pattern: /servicos
   defaults: { _controller: PmcIntranetBundle:Servico:listarServicos }
   
mostrarFuncionarios:
   pattern: /ajax/mostrarFuncionarios
   defaults: { _controller: PmcIntranetBundle:Servico:mostrarFuncionarios }    
   
novoServico:
   pattern: /admin/servico/novo
   defaults: { _controller: PmcIntranetBundle:Servico:novoServico }

editarServico:
   pattern: /admin/servicos/editar/{id}
   defaults: { _controller: PmcIntranetBundle:Servico:editarServico, id: null }  

excluirServico:
   pattern: /ajax/excluirServico
   defaults: { _controller: PmcIntranetBundle:Servico:excluirServico }     
   
solicitarServico:
   pattern: /solicitarServico/{id}
   defaults: { _controller: PmcIntranetBundle:ServicoSolicitado:solicitarServico, id: null }
   
servicosSolicitados:
   pattern: /servicosSolicitados
   defaults: { _controller: PmcIntranetBundle:ServicoSolicitado:listarServicosSolicitados }
   
finalizarSolicitacao:
   pattern: ajax/finalizarSolicitacao
   defaults: { _controller: PmcIntranetBundle:ServicoSolicitado:finalizarSolicitacao }    
   
novaPublicacao:
   pattern: /admin/{tipo}/novo
   defaults: { _controller: PmcIntranetBundle:Social:novaPublicacao }
   
editarPublicacao:
   pattern: /admin/{tipo}/editar/{id}
   defaults: { _controller: PmcIntranetBundle:Social:editarPublicacao, id: null }   
   
meusAvisos:
   pattern: /meusAvisos
   defaults: { _controller: PmcIntranetBundle:Avisos:listarMeusAvisos } 
   
novoAviso:
   pattern: /aviso/novo
   defaults: { _controller: PmcIntranetBundle:Avisos:novoAviso }
   
autocompletarUsuario:
   pattern: /ajax/autocompletarUsuario
   defaults: { _controller: PmcIntranetBundle:Avisos:autocompletarUsuario }  
   
excluirAviso:
   pattern: /ajax/excluirAviso
   defaults: { _controller: PmcIntranetBundle:Avisos:excluirAviso }    
   
lerAviso:
   pattern: /ajax/lerAviso
   defaults: { _controller: PmcIntranetBundle:Avisos:lerAviso }     