parameters:
#    pmc_intranet.example.class: Pmc\IntranetBundle\Example

services:
#    pmc_intranet.example:
#        class: %pmc_intranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
