Pmc\IntranetBundle\Entity\Publicacao:
  properties:
    imagem:        
        - Image:
            maxSize: "2M"
            maxSizeMessage: " O tamanho do arquivo não pode ser maio a 2MB "
            mimeTypes: ["image/png", "image/jpeg", "image/jpg", "image/tiff", "image/gif"]
            mimeTypesMessage: " Formato de arquivo invalido "           
    titulo:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 2
            max: 2000            
            maxMessage: " O campo não pode exceder 2000 caracteres "
            minMessage: " Deve superar 2 caracteres "
            
    resumo:
        - Length:
            min: 5
            max: 1000            
            maxMessage: " O campo não pode exceder 1000 caracteres "
            minMessage: " Deve superar 5 caracteres "
            
    conteudo:
        - Length:
            min: 5
            max: 2000            
            maxMessage: " O campo não pode exceder 2000 caracteres "
            minMessage: " Deve superar 5 caracteres "            
            
    video:        
        - Length:
            min: 5
            max: 250            
            maxMessage: " O campo não pode exceder 250 caracteres "
            minMessage: " Deve superar 5 caracteres "            
            
Pmc\IntranetBundle\Entity\Banner:
  properties:
    imagem:        
        - Image:
            maxSize: "2M"
            maxSizeMessage: " O tamanho do arquivo não pode ser maio a 2MB "
            mimeTypes: ["image/png", "image/jpeg", "image/jpg", "image/tiff", "image/gif"]
            mimeTypesMessage: " Formato de arquivo invalido "
       #     uploadIniSizeErrorMessage: "  O tamanho do arquivo invalido para o servidor "
       #     uploadFormSizeErrorMessage: "  O tamanho do arquivo não pode ser maio a 3MB "
       #     uploadErrorMessage: " erro de upload "
       # - Image:            
       #     maxWidth: 800
       #     maxHeight: 640            
    nome:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 2
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 2 caracteres "            
    url:
        - Url: {message: " URL inválida "}
        - Length:
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "            
            
Pmc\IntranetBundle\Entity\LinkUteis:
  properties:
    nome:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 5
            max: 50            
            maxMessage: " O campo não pode exceder 50 caracteres "
            minMessage: " Deve superar 5 caracteres "            
    link:
        - Url: {message: " URL inválida "}
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}        
        - Length:
            max: 50            
            maxMessage: " O campo não pode exceder 50 caracteres "
            
Pmc\IntranetBundle\Entity\LeiDecreto:
  properties:
    nome:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 5
            max: 50            
            maxMessage: " O campo não pode exceder 50 caracteres "
            minMessage: " Deve superar 5 caracteres "            
    conteudo:
        - Length:
            min: 5
            max: 2000            
            maxMessage: " O campo não pode exceder 2000 caracteres "
            minMessage: " Deve superar 5 caracteres "                  
    arquivo:      
        - File:
            maxSize: "2M"
            maxSizeMessage: " O tamanho do arquivo não pode ser maio a 2MB "
            mimeTypes: ["application/pdf", "application/x-pdf"]
            mimeTypesMessage: " Formato de arquivo invalido "  
    ano:
        - NotNull: {message: " O campo não pode ser nulo "}
        - Range:
            min: 1970
            max: 2050            
            maxMessage: " O ano não pode exceder 2050 "
            minMessage: " Ano Deve superar 1970 "  
            
Pmc\IntranetBundle\Entity\Usuario:
  properties:
    nome:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 4
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 4 caracteres "
    secretaria:
        - NotNull: {message: " Deve selecionar uma secretaria "}
        
    role:
        - Count:             
            min: 1 
            minMessage: " Deve selecionar o nível "
    email:
        - NotBlank: {message:""}
        - NotNull: {message: " O campo não pode ser nulo "}      
        - Email: {message: " Email inválido "}
        - Length: 
            min: 5
            max: 100
            minMessage: " Deve superar 5 caracteres "
            maxMessage: " O campo não pode exceder 100 caracteres "            
    cargo:
        - Length:
            min: 2
            max: 40            
            maxMessage: " O campo não pode exceder 40 caracteres "
            minMessage: " Deve superar 2 caracteres "  
    telefone:
        - Length:
            min: 3
            max: 20            
            maxMessage: " O campo não pode exceder 20 caracteres "
            minMessage: " Deve superar 3 caracteres "             
    foto:    
        - Image:
            maxSize: "2M"
            maxSizeMessage: " O tamanho do arquivo não pode ser maio a 2MB "
            mimeTypes: ["image/png", "image/jpeg", "image/jpg", "image/tiff", "image/gif"]
            mimeTypesMessage: " Formato de arquivo invalido " 
    matricula:
        - Length:
            min: 3
            max: 20            
            maxMessage: " O campo não pode exceder 20 caracteres "
            minMessage: " Deve superar 3 caracteres "
    rg:
        - Length:
            min: 3
            max: 20            
            maxMessage: " O campo não pode exceder 20 caracteres "
            minMessage: " Deve superar 3 caracteres "            
    cpf:
        - Length:
            min: 3
            max: 20            
            maxMessage: " O campo não pode exceder 20 caracteres "
            minMessage: " Deve superar 3 caracteres " 
            
Pmc\IntranetBundle\Entity\Servico:
  properties:
    nome:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 4
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 4 caracteres "
    conteudo:
        - Length:
            min: 5
            max: 2000            
            maxMessage: " O campo não pode exceder 2000 caracteres "
            minMessage: " Deve superar 5 caracteres "  
            
    secretaria:
        - NotNull: {message: " Deve selecionar uma secretaria "}
        
    responsavel:
        - Count:             
            min: 1 
            minMessage: " Deve selecionar os usuários responsáveis "
            
Pmc\IntranetBundle\Entity\SolicitacaoServico:
  properties:
    titulo:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 4
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 4 caracteres "
    conteudo:
        - Length:
            min: 5
            max: 2000            
            maxMessage: " O campo não pode exceder 2000 caracteres "
            minMessage: " Deve superar 5 caracteres "  
            
Pmc\IntranetBundle\Entity\Secretaria:
  properties:
    nome:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 4
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 4 caracteres "
    endereco:
        - Length:
            min: 5
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 5 caracteres " 
    email:     
        - Email: {message: " Email inválido "}
        - Length: 
            min: 5
            max: 100
            minMessage: " Deve superar 5 caracteres "
            maxMessage: " O campo não pode exceder 100 caracteres " 
    telefone:
        - Length:
            min: 3
            max: 20            
            maxMessage: " O campo não pode exceder 20 caracteres "
            minMessage: " Deve superar 3 caracteres " 
    urlSite:
        - Url: {message: " URL inválida "}      
        - Length:
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
    mapa:        
        - Length:
            min: 5
            max: 1500            
            maxMessage: " O campo não pode exceder 1500 caracteres "
            minMessage: " Deve superar 5 caracteres "
    secretario:
        - NotNull: {message: " Deve selecionar um secretário "}
        
Pmc\IntranetBundle\Entity\Aviso:
  properties:
    titulo:
        - NotBlank: {message: ""}
        - NotNull: {message: " O campo não pode ser nulo "}
        - Length:
            min: 4
            max: 100            
            maxMessage: " O campo não pode exceder 100 caracteres "
            minMessage: " Deve superar 4 caracteres "
    conteudo:
        - Length:
            min: 5
            max: 2000            
            maxMessage: " O campo não pode exceder 2000 caracteres "
            minMessage: " Deve superar 5 caracteres "  
        
    destinatarios:
        - Count:             
            min: 1 
            minMessage: " Selecione pelo menos um destinatário "        
            
Pmc\IntranetBundle\Entity\AvisoDestinatario:
    usuario:
        - NotNull: {message: " Deve selecionar um destinatário "}