Pmc\IntranetBundle\Entity\Secretaria:
    type: entity
    table: secretaria
    repositoryClass: Pmc\IntranetBundle\Entity\SecretariaRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Nome da Secretaria.'
            default: ''
        endereco:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Endereço da Secretaria.'
        telefone:
            type: string
            nullable: true
            length: 13
            fixed: false
            comment: 'Telefone da Secretaria.'
        urlSite:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'URL da Secretaria.'
            default: 'http://www.carapicuiba.sp.gov.br/index.php'
            column: url_site
        mapa:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'iframe com o mapa da Secretaria.'
        email:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'E-Mail da Secretaria.'
        dataCadastro:
            type: date
            nullable: false
            comment: 'Data do Cadastro no Sistema.'
            column: data_cadastro
        ativo:
            type: boolean
            nullable: false
            comment: 'Indica se o registro está ativo no sistema.'
            default: '1'
    manyToOne:
        secretario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false           
    oneToMany:
        servicos:
            targetEntity: Servico
            mappedBy: secretaria
        usuarios:
            targetEntity: Usuario
            mappedBy: secretaria              
    lifecycleCallbacks: {  }
