Pmc\IntranetBundle\Entity\Servico:
    type: entity
    table: servico
    repositoryClass: Pmc\IntranetBundle\Entity\ServicoRepository
    indexes:
        fk_secretaria_servico_idx:
            columns:
                - secretaria_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Nome do servico'
        conteudo:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Descrição do Serviço'
        data:
            type: datetime
            nullable: false
            comment: 'Data de criação do serviço'
        ativo:
            type: boolean
            nullable: false
            comment: 'Indica se o registro está ativo no sistema'
            default: '1'
    oneToMany:
        solicitacaoServico:
            targetEntity: SolicitacaoServico
            mappedBy: servico
    manyToOne:
        secretaria:
            targetEntity: Secretaria
            cascade: {  }
            mappedBy: null
            inversedBy: servicos
            joinColumns:
                secretaria_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        responsavel:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: servico
            joinTable:
                name: responsavel_servico
                joinColumns:
                    -
                        name: servico_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: usuario_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
